
%B_threshold_inputs.m

%Prepares data for MATLAB Classification Learner app 
%Statistics and Machine Learning Toolbox required
%Created 07-Apr-2018 Kevin M. Johnson, M.D. Yale University

%This code sets a percentile cutoff value for the vessel feature weights and 
%prepares tables with the remaining weights and corresponding outcomes for use
%by MATLAB Classificattion Learner App.

%In addition to the original CCTA data, this requires data from relieff_results_table 
%(a list of features in order of weights) generated by A_multiK_feature_selection.m 

%Three outcomes were defined: all deaths, coronary artery disease deaths,
%and CHD deaths plus myocardial infarctions. The variable numbering 1
%through 3 generallly refers to these three outcomes.

%load original data and relieff weights 
    load input_data/CCTAdataAugust2018
    load input_data/relieff_table
    data_table=CCTAdataAugust2018;
    
%set the desired vessel feature weight cutoff percentile
%note: to exclude features with weights <= 0, set cutoff=0 instead of using perc=0 
    parameter.percentile=25;
    
%vessel feature names and weights for each of three outcome types
    names_all1=table2array(relieff_table(:,1));
    wts1=table2array(relieff_table(:,2));
    names_all2=table2array(relieff_table(:,3));
    wts2=table2array(relieff_table(:,4));
    names_all3=table2array(relieff_table(:,5));
    wts3=table2array(relieff_table(:,6));
    
%find names of features with weights > cutoff
    if parameter.percentile>0
        cutoff=prctile(wts1,parameter.percentile);
    else
        cutoff=0;
    end
    pos=wts1>cutoff;
    names1=names_all1(pos);
    
    if parameter.percentile>0
        cutoff=prctile(wts2,parameter.percentile);
    else
        cutoff=0;
    end
    pos=wts2>cutoff;
    names2=names_all2(pos);
    
    if parameter.percentile>0
        cutoff=prctile(wts3,parameter.percentile);
    else
        cutoff=0;
    end
    pos=wts3>cutoff;
    names3=names_all3(pos);
    
%move features and outcomes into tables for Classification Learner App
%outcome occupies the last column
    outcome1=table2array(data_table(:,end-2));
    outcome2=table2array(data_table(:,end-1));
    outcome3=table2array(data_table(:,end));
    
    features1=table2array(data_table(:,names1));
    CCTAtable1=table(features1,outcome1);    
    CCTAtable1 = [array2table(table2array(CCTAtable1(:,{'features1'}))),CCTAtable1(:,setdiff(CCTAtable1.Properties.VariableNames, {'features1'}))];
    CCTAtable1.Properties.Description='All deaths, AUC with CI';
    CCTAtable1.Properties.UserData.percentile=parameter.percentile;
    
    features2=table2array(data_table(:,names2));
    CCTAtable2=table(features2,outcome2);
    CCTAtable2 = [array2table(table2array(CCTAtable2(:,{'features2'}))),CCTAtable2(:,setdiff(CCTAtable2.Properties.VariableNames, {'features2'}))];
    CCTAtable2.Properties.Description='CHD deaths, AUC with CI';
    CCTAtable2.Properties.UserData.percentile=parameter.percentile;
    
    features3=table2array(data_table(:,names3));
    CCTAtable3=table(features3,outcome3);
    CCTAtable3 = [array2table(table2array(CCTAtable3(:,{'features3'}))),CCTAtable3(:,setdiff(CCTAtable3.Properties.VariableNames, {'features3'}))];
    CCTAtable3.Properties.Description='CHD deaths + MI, AUC with CI';
    CCTAtable3.Properties.UserData.percentile=parameter.percentile;
    
%save results
    save('input_data/CCTAtable1','CCTAtable1')
    save('input_data/CCTAtable2','CCTAtable2')
    save('input_data/CCTAtable3','CCTAtable3')
    
%Next Steps:

%Data are now in the workspace and in useable form for the Classification Learner
%Go to "APPS" tab in top MATLAB GUI menu, select "Classification Learner".
%A new window will open. Select "New Session" in the upper left corner.
%Under "Workspace Variable" select "CCTAtable1" (all deaths outcome).
%Under "Cross-Validation" select 10 fold.
%Select "Start Session" in right lower corner.
%In the Classification Learner GUI, select "ROC Curve" from the menu bar.
%You are now ready to run the various models as selectable under the 
%"Model Type" icons on the menu bar.
%Repeat the process for the other two outcomes



